### ISSUE TITLE
Translation problem language contact type selector language.

### ISSUE THREAD

**Issue by Helioafer** [tastyigniter/ti-ext-frontend#1]
Translation problem language contact type selector language.

https://github.com/tastyigniter/ti-ext-frontend/blob/aa6793441839e8d323aaf5d7fd6458ba97ada2ba/components/Contact.php#L41

       $ this -> subject = [ 'Consulta general' , 'Comentario' , 'Problemas técnicos' ];

change line for

        $this->subjects = [lang('igniter.frontend::default.contact.text_general_enquiry'), lang('igniter.frontend::default.contact.text_comment'), lang('igniter.frontend::default.contact.text_technical_issues')];

**Comment by sampoyigi** [comment]
Thank you for taking the time to report and offer a solution.
