### ISSUE TITLE
[Bug]: New install, error Forbidden displays when attempting to install the frontend extension

### ISSUE THREAD

**Issue by roydeanjr** [tastyigniter/ti-ext-frontend#11]
### What happened?

Choose to install extensions in v3.5.4 and receive a Forbidden message pop up when installing frontend.

### What did you expect to happen?

A successful installation.

### Version

3.5.x

### What browser are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
No output!
```

**Comment by roydeanjr** [comment]
![2022-08-30 12_04_08-Extensions - RDQBBQ and 1 more page - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/36243458/187497665-01eb850a-a944-4c34-bc88-f62558ed667e.png)

**Comment by roydeanjr** [comment]
I even downloaded and placed the frontend extension in the extensions folder, extracted and renamed the folder to just frontend. With that I was able to start frontend, but it shows v0.1.0 and thus an upgrade is offered. Attempting to upgrade I get the same Forebidden messager.

**Comment by roydeanjr** [comment]
@sampoyigi is it possible to get some eyes on this issue?

**Comment by sampoyigi** [comment]
No issue on the update server here. If your app and extensions are up to date, you can run this command to register their updated version numbers `php artisan igniter:util set version --extensions`

**Comment by roydeanjr** [comment]
Thank you for replying. And If I do not have command line access? What would I do?

Also, what folders are being access denied? I get a PHP Fileinfo extension error in the system log now.

**Comment by roydeanjr** [comment]
I attempted changing permissions to 777 and the whole site stopped working. I had to delete all files and run setup again. Why do all other extensions install just fine and frontend is the only one that fails?

**Comment by roydeanjr** [comment]
fileinfo is installed, but this message displays in the system log in TI:


Intervention\Image\Exception\MissingDependencyException: PHP Fileinfo extension must be installed/enabled to use Intervention Image.in /home/ardeec92/public_html/rdq/vendor/intervention/image/src/Intervention/Image/ImageManager.php:137

**Comment by roydeanjr** [comment]
I give up!
